import { defineConfig } from "tsup";

export default defineConfig({
    entry: ["src/index.ts"],
    outDir: "dist",
    sourcemap: true,
    clean: true,
    format: ["esm"],
    noExternal: ["playwright-core", "puppeteer", "puppeteer-core", "ws"],
    external: [
        "dotenv",
        "fs",
        "path",
        "@reflink/reflink",
        "@node-llama-cpp",
        "https",
        "http",
        "agentkeepalive",
        "stream",
        "whatwg-url",
        "util",
        "events",
        "os",
        "crypto",
        "buffer",
        "url",
        "zlib",
        "net",
        "tls",
        "assert",
        "child_process",
        "worker_threads",
        "perf_hooks",
        "querystring",
        "dns",
        "punycode",
        "tty",
        "constants",
        "string_decoder",
        "playwright-core",
        "playwright",
        "playwright-firefox",
        "playwright-chromium",
        "playwright-webkit",
        "node:stream",
        "node:util",
        "node:events",
        "node:os",
        "node:crypto",
        "node:buffer",
        "node:url",
        "node:zlib",
        "node:net",
        "node:tls",
        "node:assert",
        "node:child_process",
        "node:worker_threads",
        "node:perf_hooks",
        "node:querystring",
        "node:dns",
        "node:punycode",
        "node:tty",
        "node:constants",
        "node:string_decoder",
    ],
    esbuildOptions(options) {
        options.platform = "node";
        options.target = "node18";
        options.mainFields = ["module", "main"];
        options.conditions = ["import", "module", "require", "default"];
        options.define = {
            "process.env.NODE_DEBUG": "false",
        };
    },
});
